set default="1"

function load_video {
  insmod efi_gop
  insmod efi_uga
  insmod video_bochs
  insmod video_cirrus
  insmod all_video
  insmod png
}

load_video
set gfxpayload=keep
background_image /EFI/boot/splash.png
insmod gzio
insmod part_gpt
insmod ext2

set timeout=60
### END /etc/grub.d/00_header ###

search --no-floppy --set=root -l '%NEW_ISO_LABEL%'

### BEGIN /etc/grub.d/10_linux ###
menuentry 'Install SEALFAIL %ALMA_VERSION%' --class fedora --class gnu-linux --class gnu --class os {
        linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=%NEW_ISO_LABEL% quiet inst.ks=hd:LABEL=%NEW_ISO_LABEL%:/%PATH_KICKSTART_MAIN%
        initrdefi /images/pxeboot/initrd.img
}
